# Generated by Django 5.2.17 on 2026-09-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_backfill_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_picture',
            field=models.TextField(blank=True, default=''),
        ),
    ]
