# Generated by Django 5.2.17 on 2026-09-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='record_id',
            field=models.IntegerField(blank=True, help_text='Id del viaje o de la carga que originó el aviso. Permite abrir el registro puntual y resaltarlo, en vez de llevar a una pantalla genérica.', null=True),
        ),
    ]
